name: Check Outputs
on: push
jobs:
  set_output:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.set.outputs.message }}
    steps:
    - name: Set output
      id: set
      run: echo "message=hello" >> "$GITHUB_OUTPUT"

  read_output:
    runs-on: ubuntu-latest
    needs: set_output
    steps:
      - name: Read output
        run: echo "$GITHUB_OUTPUT"
      - name: Check message
        env:
          MESSAGE: ${{ needs.set_output.outputs.message }}
        run: echo "$MESSAGE"

