name: Release
on: push
jobs:
  set_output:
    runs-on: ubuntu-latest
    steps:
    - name: Set output
      run: echo "message=hello" >> "$GITHUB_OUTPUT"

  read_output:
    runs-on: ubuntu-latest
    needs: set_output
    steps:
      - name: Read output
        run: echo "$GITHUB_OUTPUT"
      - name: Check message
        env:
          MESSAGE: ${{ needs.set_output.outputs.VERSION }}
        run: echo "$MESSAGE"

