name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Type of version to release"
        required: true
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.set-version.outputs.VERSION }}
    steps:
    - uses: actions/checkout@v4
    # - name: Setup git config
    #   run: |
    #     git config user.name "github-actions[bot]"
    #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Prepare release
      run: |
        npm version ${{ github.event.inputs.release_type }}
        git push
        npm pack
    - name: Set version output
      id: set-version
      run: echo "VERSION=v$(npm pkg get version | tr -d \")" >> "$GITHUB_OUTPUT"
    - uses: actions/upload-artifact@v4
      with:
        path: '*.tgz'

  release:
    runs-on: ubuntu-latest
    needs: bump
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          VERSION: ${{ needs.bump.outputs.VERSION }}
        run: gh release create $VERSION artifact/*.tgz --generate-notes
